### ISSUE TITLE
iframe Viewport

### ISSUE THREAD

**Issue by designerbrent** [adventistchurch/igs-guidelines#7]
It would be helpful for the iFrame on the component display to size to the correct height of the item getting displayed in it.

**Comment by tpitre** [comment]
@designerbrent This is working for me, is it not for you? If not, can you check to see if there's any console errors?

![img](http://d.pr/i/mt0QBL+)

**Comment by tpitre** [comment]
Ok, I think I may have just fixed it. You'll have to pull in the ALPS `178-style-guide-guide` branch and run `grunt style-guide-export` to get the latest build which includes the iframe map file. I think I had it a gitignored directory and it wasn't being added to the repo. This should do it for you.

**Comment by designerbrent** [comment]
That did it. I had to regenerate the ALPS files, `grunt prod` before running the `grunt style-guide-export` but other then that, it works fine now.
